#ifndef IRENDERSYSTEM_GLOBAL_H
#define IRENDERSYSTEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IRENDERSYSTEM_LIBRARY)
#  define IRENDERSYSTEMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IRENDERSYSTEMSHARED_EXPORT Q_DECL_IMPORT
#endif

#define IRENDERSYSTEM_NAMESPACE NIRenderSystem
#define IRENDERSYSTEM_BEGIN_NAMESPACE namespace IRENDERSYSTEM_NAMESPACE {
#define IRENDERSYSTEM_END_NAMESPACE }

#endif // IRENDERSYSTEM_GLOBAL_H
