#ifndef COMMANDSTORE_GLOBAL_H
#define COMMANDSTORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMANDSTORE_LIBRARY)
#  define COMMANDSTORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMANDSTORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMANDSTORE_GLOBAL_H
