#ifndef CONTAINERS_GLOBAL_H
#define CONTAINERS_GLOBAL_H

#define CONTAINERS_NAMESPACE Containers
#define CONTAINERS_BEGIN_NAMESPACE namespace CONTAINERS_NAMESPACE {
#define CONTAINERS_END_NAMESPACE }

#endif // CONTAINERS_GLOBAL_H

