#ifndef IRENDERDATA_GLOBAL_H
#define IRENDERDATA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IRENDERDATA_LIBRARY)
#  define IRENDERDATASHARED_EXPORT Q_DECL_EXPORT
#else
#  define IRENDERDATASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IRENDERDATA_GLOBAL_H
