#ifndef SERIALISATION_GLOBAL_H
#define SERIALISATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALISATION_LIBRARY)
#  define SERIALISATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERIALISATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#define SERIALISATION_NAMESPACE Serialisation
#define SERIALISATION_BEGIN_NAMESPACE namespace SERIALISATION_NAMESPACE {
#define SERIALISATION_END_NAMESPACE }

#endif // SERIALISATION_GLOBAL_H
